import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import variables from "./variables.module.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const c = "cyan";
    console.log(variables);

    return (
        <html lang="en">
            <body className={inter.className} style={{ background: variables.primaryColor }}>
                {children}
            </body>
        </html>
    );
}
